public partial class AppMain
{
    private enum AME_IPHONE_DISPLAY_ORIENTATION
    {
        AME_IPHONE_DISPLAY_ORIENTATION_NORMAL,
        AME_IPHONE_DISPLAY_ORIENTATION_RIGHT,
        AME_IPHONE_DISPLAY_ORIENTATION_HORIZON,
        AME_IPHONE_DISPLAY_ORIENTATION_LEFT,
        AME_IPHONE_DISPLAY_ORIENTATION_NUM,
    }
}
