public partial class AppMain
{
    public enum DME_LOGO_COM_LOAD_STATE
    {
        DMD_LOGO_COM_LOAD_STATE_LOAD_WAIT,
        DMD_LOGO_COM_LOAD_STATE_LOADING,
        DMD_LOGO_COM_LOAD_STATE_COMPLETE,
        DMD_LOGO_COM_LOAD_STATE_ERROR,
        DMD_LOGO_COM_LOAD_STATE_MAX,
    }
}
