public partial class AppMain
{
    private enum DME_TITLE_WIN_TYPE
    {
        DME_TITLE_WIN_TYPE_DEL_DATA1,
        DME_TITLE_WIN_TYPE_DEL_DATA2,
        DME_TITLE_WIN_TYPE_DEL_DATA3,
        DME_TITLE_WIN_TYPE_DEL_DATA4,
        DME_TITLE_WIN_TYPE_DEL_DATA5,
        DME_TITLE_WIN_TYPE_MAX,
        DME_TITLE_WIN_TYPE_NONE,
    }
}
