public partial class AppMain
{
    private enum DME_TITLE_MENU_TYPE
    {
        DME_TITLE_MENU_TYPE_START,
        DME_TITLE_MENU_TYPE_TUDUKI,
        DME_TITLE_MENU_TYPE_OPTION,
        DME_TITLE_MENU_TYPE_ACHIEVEMENTS,
        DME_TITLE_MENU_TYPE_LEADERBOARDS,
        DME_TITLE_MENU_TYPE_NUM,
        DME_TITLE_MENU_TYPE_NONE,
    }
}
