public partial class AppMain
{
    private enum DME_FILESLCT_NEXT_EVT
    {
        DME_FILESLCT_NEXT_EVT_MAINGAME,
        DME_FILESLCT_NEXT_EVT_OPTION,
        DME_FILESLCT_NEXT_EVT_MAINMENU,
        DME_FILESLCT_NEXT_EVT_TITLE,
        DME_FILESLCT_NEXT_EVT_MAX,
    }
}
