public partial class AppMain
{
    private enum DME_TITLE_NEXT_EVT
    {
        DME_TITLE_NEXT_EVT_MAINGAME_1_1,
        DME_TITLE_NEXT_EVT_STAGESELECT,
        DME_TITLE_NEXT_EVT_OPTION,
        DME_TITLE_NEXT_EVT_RANKING,
        DME_TITLE_NEXT_EVT_LOGO,
        DME_TITLE_NEXT_EVT_TITLE,
        DME_TITLE_NEXT_EVT_MAX,
        DME_TITLE_NEXT_EVT_NONE,
    }
}
