public partial class AppMain
{
    private enum DME_FILESLCT_SAVE_FILE
    {
        DME_FILESLCT_SAVE_FILE_1,
        DME_FILESLCT_SAVE_FILE_2,
        DME_FILESLCT_SAVE_FILE_3,
        DME_FILESLCT_SAVE_FILE_4,
        DME_FILESLCT_SAVE_FILE_5,
        DME_FILESLCT_SAVE_FILE_6,
        DME_FILESLCT_SAVE_FILE_NUM,
        DME_FILESLCT_SAVE_FILE_NONE,
    }
}
