using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using accel;
using dbg;
using er;
using er.web;
using gs;
using gs.backup;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Graphics.PackedVector;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Media;
using mpp;
using setting;

public partial class AppMain
{
    private class DMS_STGSLCT_MAIN_WORK
    {
        public readonly AppMain.AMS_FS[] arc_cmn_amb_fs = new AppMain.AMS_FS[5];
        public readonly AppMain.AMS_AMB_HEADER[] arc_cmn_amb = new AppMain.AMS_AMB_HEADER[5];
        public readonly AppMain.A2S_AMA_HEADER[] cmn_ama = new AppMain.A2S_AMA_HEADER[5];
        public readonly AppMain.AMS_AMB_HEADER[] cmn_amb = new AppMain.AMS_AMB_HEADER[5];
        public readonly AppMain.AOS_TEXTURE[] cmn_tex = AppMain.New<AppMain.AOS_TEXTURE>(5);
        public readonly AppMain.AMS_FS[] arc_amb_fs = new AppMain.AMS_FS[2];
        public readonly AppMain.AMS_AMB_HEADER[] arc_amb = new AppMain.AMS_AMB_HEADER[2];
        public readonly AppMain.A2S_AMA_HEADER[] ama = new AppMain.A2S_AMA_HEADER[2];
        public readonly AppMain.AMS_AMB_HEADER[] amb = new AppMain.AMS_AMB_HEADER[2];
        public readonly AppMain.AOS_TEXTURE[] tex = AppMain.New<AppMain.AOS_TEXTURE>(2);
        public readonly AppMain.AOS_TEXTURE win_tex = new AppMain.AOS_TEXTURE();
        public readonly AppMain.AOS_ACTION[] act = new AppMain.AOS_ACTION[116];
        public readonly CTrgAoAction[] trg_zone = AppMain.New<CTrgAoAction>(6);
        public readonly CTrgAoAction[] trg_act = AppMain.New<CTrgAoAction>(7);
        public readonly CTrgAoAction[] trg_act_tab = AppMain.New<CTrgAoAction>(6);
        public readonly CTrgAoAction[] trg_act_lr = AppMain.New<CTrgAoAction>(2);
        public readonly CTrgFlick trg_act_move = new CTrgFlick();
        public readonly CTrgAoAction[] trg_mode = AppMain.New<CTrgAoAction>(2);
        public readonly CTrgAoAction trg_cancel = new CTrgAoAction();
        public readonly CTrgAoAction[] trg_answer = AppMain.New<CTrgAoAction>(2);
        public readonly int[] n_sonic_hi_score = new int[17];
        public readonly int[] s_sonic_hi_score = new int[17];
        public readonly int[] n_sonic_record_time = new int[17];
        public readonly int[] s_sonic_record_time = new int[17];
        public readonly int[] hi_score = new int[24];
        public readonly int[] record_time = new int[24];
        public readonly int[] is_clear_stage = new int[24];
        public readonly uint[] eme_stage_no = new uint[7];
        public readonly float[,] win_act_pos = new float[13, 2];
        public readonly float[] win_size_rate = new float[2];
        public readonly float[][] zone_pos = AppMain.New<float>(6, 2);
        public readonly float[] move_spd = new float[2];
        public readonly float[] act_top_pos_x = new float[24];
        public readonly float[] act_top_pos_y = new float[24];
        public readonly float[] act_move_src = new float[2];
        public readonly float[] act_move_dest = new float[2];
        public readonly float[] act_move_pos_src = new float[24];
        public readonly float[] act_move_pos_dst = new float[24];
        public readonly float[] act_tab_state_move_base_pos = new float[2];
        public readonly float[] obi_pos = new float[2];
        public readonly AppMain.AMS_PARAM_DRAW_PRIMITIVE up_bg_vrtx = new AppMain.AMS_PARAM_DRAW_PRIMITIVE();
        public readonly float[] tex_u = new float[2];
        public readonly float[] tex_v = new float[2];
        public AppMain.AMS_FS win_amb_fs;
        public AppMain.AMS_AMB_HEADER win_amb;
        public AppMain.DMS_STGSLCT_MAIN_WORK._proc_win_input_ proc_win_input;
        public AppMain.DMS_STGSLCT_MAIN_WORK._proc_input_ proc_input;
        public AppMain.DMS_STGSLCT_MAIN_WORK._proc_win_update_ proc_win_update;
        public AppMain.DMS_STGSLCT_MAIN_WORK._proc_menu_update_ proc_menu_update;
        public AppMain.DMS_STGSLCT_MAIN_WORK._proc_draw_ proc_draw;
        public int timer;
        public uint flag;
        public int state;
        public float win_timer;
        public uint disp_flag;
        public int bg_timer;
        public int zone_scr_timer;
        public uint announce_flag;
        public int next_evt;
        public int prev_evt;
        public int is_final_open;
        public uint get_emerald;
        public uint cur_game_mode;
        public uint player_stock;
        public int win_mode;
        public int win_cur_slct;
        public bool win_is_disp_cover;
        public uint cur_zone;
        public uint chng_zone;
        public uint efct_time;
        public uint efct_out_flag;
        public float chaos_eme_pos_y;
        public float mode_tex_pos_y;
        public float mode_tex_frm;
        public int cur_stage;
        public int prev_stage;
        public int cur_vrtcl_stage;
        public int prev_vrtcl_stage;
        public int crsr_idx;
        public int crsr_prev_idx;
        public float crsr_pos_y;
        public float crsr_move_src;
        public float crsr_move_dst;
        public int focus_disp_no;
        public int prev_disp_no;
        public bool is_disp_cover;
        public int decide_zone_efct_dist_x;
        public int decide_zone_efct_dist_y;
        public AppMain.AOS_ACT_COL bg_fade;
        public uint cur_bg_id;
        public uint next_bg_id;
        public uint zone_scr_id;
        public uint mode_tex_move_frm;
        public uint btn_l_disp_frm;
        public uint btn_r_disp_frm;
        public bool is_jp_region;

        public delegate void _proc_win_input_(AppMain.DMS_STGSLCT_MAIN_WORK work);

        public delegate void _proc_input_(AppMain.DMS_STGSLCT_MAIN_WORK work);

        public delegate void _proc_win_update_(AppMain.DMS_STGSLCT_MAIN_WORK work);

        public delegate void _proc_menu_update_(AppMain.DMS_STGSLCT_MAIN_WORK work);

        public delegate void _proc_draw_(AppMain.DMS_STGSLCT_MAIN_WORK work);
    }
}
