public partial class AppMain
{
    public enum GMD_MAIN_NEXT_EVT
    {
        GMD_MAIN_NEXT_EVT_WORLDMAP,
        GMD_MAIN_NEXT_EVT_MAINGAME,
        GMD_MAIN_NEXT_EVT_ENDING,
        GMD_MAIN_NEXT_EVT_SPSTAGE_BRA,
        GMD_MAIN_NEXT_EVT_MAINMENU,
        GMD_MAIN_NEXT_EVT_TITLE,
        GMD_MAIN_NEXT_EVT_BUYSCREEN,
        GMD_MAIN_NEXT_EVT_MAX,
    }
}
