public partial class AppMain
{
    public enum GME_GAMEDAT_LOAD_PROGRESS
    {
        GMD_GAMEDAT_LOAD_PROGRESS_NOLOAD,
        GMD_GAMEDAT_LOAD_PROGRESS_LOADING,
        GMD_GAMEDAT_LOAD_PROGRESS_LOADFINISH,
        GMD_GAMEDAT_LOAD_PROGRESS_COMPLETE,
        GMD_GAMEDAT_LOAD_PROGRESS_MAX,
    }
}
