public partial class AppMain
{
    public enum GME_GAME_DBUILD_MDL_STATE
    {
        GME_GAME_DBUILD_MDL_STATE_REG_WAIT,
        GME_GAME_DBUILD_MDL_STATE_BUILD_WAIT,
        GME_GAME_DBUILD_MDL_STATE_REG_FLUSH_WAIT,
        GME_GAME_DBUILD_MDL_STATE_FLUSH_WAIT,
        GME_GAME_DBUILD_MDL_STATE_MAX,
    }
}
