public partial class AppMain
{
    public enum GME_GAMEDAT_LOAD_STATE
    {
        GMD_GAMEDAT_LOAD_STATE_LOADING,
        GMD_GAMEDAT_LOAD_STATE_LOADFINISH,
        GMD_GAMEDAT_LOAD_STATE_COMPLETE,
        GMD_GAMEDAT_LOAD_STATE_ERROR,
        GMD_GAMEDAT_LOAD_STATE_MAX,
    }
}
