public partial class AppMain
{
    private class NNS_SHADER_MANAGER
    {
        public NNS_SHADER_NAME Name;
        public NNE_SHADERTYPE ShaderType;
        public uint ProgramObject;
        public uint VertexProgram;
        public uint FragmentProgram;
        public int NumParallelLightLocation;
        public int NumPointLightLocation;
        public int NumSpotLightLocation;
        public int PointLightFallOffEndLocation;
        public int PointLightFallOffScaleLocation;
        public int SpotLightFallOffEndLocation;
        public int SpotLightFallOffScaleLocation;
        public int SpotLightAngleScaleLocation;
        public int TexBaseAlphaLocation;
        public int TexDecalAlphaLocation;
        public int TexDecal2AlphaLocation;
        public int TexDecal3AlphaLocation;
        public int TexShininessLevelLocation;
        public int TexDualParaboloidLevelLocation;
        public int TexAddLevelLocation;
        public int TexShadowColorLocation;
        public int TexShadow2ColorLocation;
        public int TexUser1ParamLocation;
        public int TexUser2ParamLocation;
        public int TexUser3ParamLocation;
        public int TexUser4ParamLocation;
        public int TexUser5ParamLocation;
        public int TexUser6ParamLocation;
        public int TexUser7ParamLocation;
        public int TexUser8ParamLocation;
        public int TexNormalSamplerLocation;
        public int TexBaseSamplerLocation;
        public int TexDecalSamplerLocation;
        public int TexDecal2SamplerLocation;
        public int TexDecal3SamplerLocation;
        public int TexSpecularSamplerLocation;
        public int TexShininessSamplerLocation;
        public int TexDualParaboloidSamplerLocation;
        public int TexEnvMaskSamplerLocation;
        public int TexModulateSamplerLocation;
        public int TexAddSamplerLocation;
        public int TexOpacitySamplerLocation;
        public int TexUser1SamplerLocation;
        public int TexUser2SamplerLocation;
        public int TexUser3SamplerLocation;
        public int TexUser4SamplerLocation;
        public int TexUser5SamplerLocation;
        public int TexUser6SamplerLocation;
        public int TexUser7SamplerLocation;
        public int TexUser8SamplerLocation;
        public int TexShadowSamplerLocation;
        public int TexShadow2SamplerLocation;
        public int TexUserSampler2D1Location;
        public int TexUserSampler2D2Location;
        public int TexUserSampler3D1Location;
        public int TexUserSampler3D2Location;
        public int TexUserSamplerCube1Location;
        public int TexUserSamplerCube2Location;
        public int DualParaboloidMatrixLocation;
        public int UserUniformLocation;
        public int PositionMatrixLocation;
        public int NormalMatrixLocation;
    }
}
