public partial class AppMain
{
    public enum OBD_DRAW_USER_COMMAND_SORT_3DNN
    {
        OBD_DRAW_USER_COMMAND_SORT_3DNN_MODEL,
        OBD_DRAW_USER_COMMAND_SORT_3DNN_MATMTN,
        OBD_DRAW_USER_COMMAND_SORT_3DNN_MAX,
    }
}
