public partial class AppMain
{
    public enum OBD_DRAW_USER_COMMAND_3DNN
    {
        OBD_DRAW_USER_COMMAND_3DNN_MODEL,
        OBD_DRAW_USER_COMMAND_3DNN_MODEL_MATMTN,
        OBD_DRAW_USER_COMMAND_3DNN_MOTION,
        OBD_DRAW_USER_COMMAND_3DNN_MOTION_MATMTN,
        OBD_DRAW_USER_COMMAND_3DNN_SET_CAMERA,
        OBD_DRAW_USER_COMMAND_3DNN_USER_FUNC,
        OBD_DRAW_USER_COMMAND_3DNN_DRAW_MOTION,
        OBD_DRAW_USER_COMMAND_3DNN_DRAW_MOTION_MATMTN,
        OBD_DRAW_USER_COMMAND_3DNN_MAX,
    }
}
